# Generated by Django 5.0.1 on 2024-10-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('lifestyle_score', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('insurance_risk_score', models.FloatField(null=True)),
                ('diabetes_risk_score', models.FloatField(null=True)),
            ],
        ),
    ]
